const orderByFields = [
   { label: 'Risk ID', field: 'Risk_ID', order: 'asc' },
   { label: 'Fiscal Year', field: 'FiscalYear', order: 'asc' },
   { label: 'Quarter', field: 'Quarter', order: 'asc' },
   { label: 'Department', field: 'Department', order: 'asc' },
   { label: 'Directorate', field: 'Directorate', order: 'asc' },
   { label: 'Division', field: 'Division', order: 'asc' },
   { label: 'Objectives', field: 'Objectives', order: 'asc' },
   { label: 'Risk Category L1', field: 'RiskCategoryL1', order: 'asc' },
   { label: 'Risk Category L2', field: 'RiskCategoryL2', order: 'asc' },
   { label: 'Risk Category L3', field: 'RiskCategoryL3', order: 'asc' },
   { label: 'Risk Event', field: 'RiskEvent', order: 'asc' },
   { label: 'Inherent Likelihood Category', field: 'InherentLikelihoodCategory', order: 'asc' },
   { label: 'Inherent Likelihood Rating', field: 'InherentLikelihoodRating', order: 'asc' },
   { label: 'Inherent Likelihood Justification', field: 'InherentLikelihoodJustification', order: 'asc' },
   { label: 'Inherent Likelihood Existing Ctrl Cat', field: 'InherentLikelihoodExisitingCtrlCat', order: 'asc' },
   { label: 'Inherent Risk Score', field: 'InherentRiskScore', order: 'asc' },
   { label: 'Inherent Risk Score Description', field: 'InherentRiskScoreDescription', order: 'asc' },
   { label: 'Inherent Impact Rating', field: 'InherentImpactRating', order: 'asc' },
   { label: 'Residual Impact Rating', field: 'ResidualImpactRating', order: 'asc' },
   { label: 'Residual Likelihood Rating', field: 'ResidualLikelihoodRating', order: 'asc' },
   { label: 'Residual Risk Score', field: 'ResidualRiskScore', order: 'asc' },
   { label: 'Residual Risk Score Description', field: 'ResidualRiskScoreDescription', order: 'asc' },
   { label: 'Agg Flag', field: 'AggFlag', order: 'asc' },
   { label: 'Risk Status', field: 'RiskStatus', order: 'asc' },
   { label: 'Agg Priority', field: 'AggPriority', order: 'asc' },
   { label: 'Dpt Priority', field: 'DptPriority', order: 'asc' },
   { label: 'Asc Priority', field: 'AscPriority', order: 'asc' },
];

export default orderByFields;